network:
  version: 2
  ethernets:
    eth2:
      dhcp4: false
  vlans:
    eth2.10:
      id: 10
      link: eth2
    eth2.20:
      id: 20
      link: eth2
    eth2.30:
      id: 30
      link: eth2
    eth2.40:
      id: 40
      link: eth2
  bridges:
    br-mgmt:
      addresses:
        - 172.29.236.11/22
      interfaces:
        - eth2.10
      mtu: 1500
    br-storage:
      addresses:
        - 172.29.244.11/22
      interfaces:
        - eth2.20
      mtu: 1500
    br-vxlan:
      addresses:
        - 172.29.240.11/22
      interfaces:
        - eth2.30
      mtu: 1500
    br-ext:
      addresses:
        - 172.17.0.11/16
      interfaces:
        - eth2
      gateway4: 172.17.0.1
      nameservers:
        addresses:
          - 172.17.0.1
      mtu: 1500
    br-vlan:
      interfaces:
        - eth2.40
      mtu: 1500
