network:
  version: 2
  ethernets:
    eth2:
      dhcp4: false
  vlans:
    eth2.10:
      id: 10
      link: eth2
  bridges:
    br-mgmt:
      addresses:
        - 172.29.236.10/22
      interfaces:
        - eth2.10
      mtu: 1500
    br-ext:
      addresses:
        - 172.17.0.10/16
      interfaces:
        - eth2
      mtu: 1500
      gateway4: 172.17.0.1
      nameservers:
        addresses:
          - 172.17.0.1
